# Generated by Django 5.0.1 on 2024-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
